# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 09:03
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiChoiceAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'MultiChoiceAnswers',
            },
        ),
        migrations.CreateModel(
            name='MultiChoiceOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'MultiChoiceOptions',
            },
        ),
        migrations.CreateModel(
            name='MultiChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('q_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='question')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MultiChoiceQuestion',
            },
        ),
        migrations.CreateModel(
            name='OneWordAnswerAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'OneWordAnswer_Answer',
            },
        ),
        migrations.CreateModel(
            name='OneWordAnswerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('q_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='question')),
                ('hint', models.CharField(max_length=60)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OneWordAnswerType',
            },
        ),
        migrations.CreateModel(
            name='SingleChoiceAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'SingleChoiceAnswer',
            },
        ),
        migrations.CreateModel(
            name='SingleChoiceOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'SingleChoiceOptions',
            },
        ),
        migrations.CreateModel(
            name='SingleChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('q_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='question')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SingleChoiceQuestion',
            },
        ),
        migrations.AddField(
            model_name='singlechoiceoptions',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SingleChoiceQuestion'),
        ),
        migrations.AddField(
            model_name='singlechoiceanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SingleChoiceOptions'),
        ),
        migrations.AddField(
            model_name='singlechoiceanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.SingleChoiceQuestion'),
        ),
        migrations.AddField(
            model_name='onewordansweranswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.OneWordAnswerType'),
        ),
        migrations.AddField(
            model_name='multichoiceoptions',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MultiChoiceQuestion'),
        ),
        migrations.AddField(
            model_name='multichoiceanswers',
            name='answers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MultiChoiceOptions'),
        ),
        migrations.AddField(
            model_name='multichoiceanswers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.MultiChoiceQuestion'),
        ),
    ]
